[project]
name = "IsThisStockGood"
version = "0.1.0"
description = ""
authors = [{ name = "Mark Klara" }]
requires-python = "~=3.9"
readme = "README.md"
dependencies = [
    "requests-futures>=1.0.1,<2",
    "wheel>=0.43.0,<0.44",
    "lxml>=5.2.2,<6",
    "flask==3.0.3",
    "virtualenv>=20.26.6,<21",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2,<9",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pylint]
indent-string="  "

[tool.pylint.messages_control]
disable = [
  "missing-docstring",
  "invalid-name",
]
